---
version: '3'
services:
  binance_new_coins:
    image: jccs/binance_new_coins:develop
    build:
       context: .
    container_name: binance_new_coins
    volumes:
      -  "./user_data:/binance_new_coins/user_data"
    # Default command used when running `docker compose up`
    command:
      python3 main.py --user-data-dir "/binance_new_coins/user_data"
